services:
services:
  - type: web
    name: your-service-name
    env: php
    plan: free
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:$PORT -t C:/xampp/htdocs/abc"
    envVars:
      - key: PORT
        value: "1000"
